import streamlit
streamlit.title(" My Parents New Healthy Diner")
streamlit.header(" Breakfast Menu")
streamlit.text(" Poha ")
streamlit.text(" Idli")
streamlit.text(" Avacado on the toast")
streamlit.text(" Egg omellette ")
streamlit.text('Omega 3 & Blueberry Oatmeal')
streamlit.text('Kale, Spinach & Rocket Smoothie')
streamlit.text('Hard-Boiled Free-Range Egg')
